In [1]:
import pandas as pd

In [2]:
layers=pd.read_csv('/home/ahmed/docker_emse/csv/compact.csv.gz', 
                            sep=',', 
                            dtype=object, 
                            index_col=None,
                            error_bad_lines=False)

layers['added']=layers['added'].apply(int)
layers['layers']=layers['layers'].apply(int)

print(len(layers))
layers.head(2)

5741475

,image,kind,hash,layers,added,depends
0,library:php:7.2-rc-cli,official,81865043194a815422936872b7fc04f3f44b6f9a399d2a...,7,7,NaN
1,library:crate:0.57.5,official,df374273de4cc39786978916764a788d6b6198f7af1bcf...,8,7,d24fd36438e5fa304feca7e01bb1b5ef9a23e993fd3433...

In [3]:
layers.query('hash =="931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761ea96c1f2c13b8b6659"')

,image,kind,hash,layers,added,depends
78230,alexl:host:latest,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
89808,cpuguy83:demo-vfs-graphdriver-plugin:latest,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
2602168,stratum:ncurses-dev:latest,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
3563703,xiaozi2006:centos:latest,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
3902615,mavenugo:test-docker-netplugin:tibor,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
4363612,cloudflavor:miniovol:latest,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
5255181,shivaraj18:scratch:latest,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
5399685,webwurst:scratch:latest,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
5407490,sourcestream:blank:latest,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
5411612,r2dev:minimal:1.1,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
5429164,intersoftlab:data-volume:latest,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
5482946,hustcts:testimage-02:latest,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
5485441,railsme:dfs:clean,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
5529555,idcu:idcu:v0,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
5554802,ijrandom:scratch:latest,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
5558243,heimergroup:misc:empty,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
5559223,ijrandom:scratch2:latest,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
5574207,shykes:gordon:latest,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
5627470,miranext:logistika-dbvolume:latest,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
5631740,cloudposse:data-vol:latest,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
5643157,danielguerra:scratch:latest,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
5645703,axeclbr:data:latest,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
5667382,michaelbudd:mb-lamp-stack:latest,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
5671141,icecrimetest:foo:v2,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
5671758,dynamind:data-only:latest,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
5677404,nancyaggarwal:custom:latest,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
5682294,conman:apps:base,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
5691566,codefreshio:status-page:latest1,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
5710156,r2dev:minimal:1.0,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
5715347,jlhawn:foobarbaz:latest,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN
5728948,mookas:empty:latest,community,931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761...,1,1,NaN

In [4]:
images = pd.read_csv('/home/ahmed/docker_emse/csv/community_images.csv')

In [20]:
images.head(10).eval('twice = popularity * 2')

                                      slug  popularity  twice
0                                  0000/..           0      0
1                                 0000/...          14     28
2                                0000/0000         147    294
3                   0000/00000000000000000           0      0
4                                 0000/_-.           0      0
5                              0000/abcdef           2      4
6                       0000/secret-wookie           0      0
7                        0000000000zw/mdga          86    172
8  0000000001/suivipag_backup_08_mars_2018          18     36
9                           00000000mia/cm          13     26

In [22]:
im = layers.query('hash =="931040ffeedc9148b2ed852bc1a9531af141a6bc1f4761ea96c1f2c13b8b6659"').image.str.rsplit(':', n=1, expand=True).rename(columns={0:'slug'}).assign(slug=lambda d: d.slug.str.replace(':', '/')).slug

In [24]:
mask = images.slug.isin(im)
images[mask]

                                         slug  popularity
93659                              alexl/host         163
208792                           axeclbr/data         126
381486                   cloudflavor/miniovol          72
382970                    cloudposse/data-vol          77
392315                codefreshio/status-page      668410
402198                            conman/apps         406
413085   cpuguy83/demo-vfs-graphdriver-plugin          95
447815                   danielguerra/scratch          69
575602                     dynamind/data-only          89
802530                       heimergroup/misc          54
841192                   hustcts/testimage-02          57
855476                       icecrimetest/foo          79
857728                              idcu/idcu         125
864166                       ijrandom/scratch          76
864167                      ijrandom/scratch2          73
883404               intersoftlab/data-volume          83
968897                       jlhawn/foobarbaz          83
1243720        mavenugo/test-docker-netplugin        3557
1276775             michaelbudd/mb-lamp-stack          57
1293370           miranext/logistika-dbvolume          71
1316468                          mookas/empty          66
1358862                  nancyaggarwal/custom          62
1559944                         r2dev/minimal        2862
1568317                           railsme/dfs         131
1747425                    shivaraj18/scratch           1
1755702                         shykes/gordon          84
1804429                    sourcestream/blank         170
1841541                   stratum/ncurses-dev          14
2065823                      webwurst/scratch          67
2105374                     xiaozi2006/centos           4

In [65]:
len(layers[['image','hash']].set_index('image').drop_duplicates())

4077958

### Let's identify the images that are required to build other images

In [32]:
# identify unique images
list_images = (layers
                 .drop(['kind','layers','added','depends'], axis=1)
                 .rename(columns={'image':'requires','hash':'depends'})
                 .set_index('requires')
                 .drop_duplicates()
                 .reset_index())

In [35]:
# Merge hash with depends
layers = (layers
          .drop(['kind','layers','added'], axis=1)
          .dropna()
          .merge(list_images,
                 on='depends',
                 how='left')
         )

In [59]:
layers.query('image == "library:tomcat:8.5.23"')

,image,hash,depends,requires
13716,library:tomcat:8.5.23,294eeadc5db0462c47812fce37a5cbc21f7a696759bdfc...,ac7be225abad43f3ca9ee99a790a14350406cf90abb271...,rajeevgup689:get-started:openjdk

In [62]:
layers.query('image == "library:tomcat:8.5.23"')

,image,hash,depends,requires
13716,library:tomcat:8.5.23,294eeadc5db0462c47812fce37a5cbc21f7a696759bdfc...,ac7be225abad43f3ca9ee99a790a14350406cf90abb271...,rajeevgup689:get-started:openjdk

In [39]:
community_layers=pd.read_csv('/home/ahmed/docker_emse/csv/layers_community.csv', 
                            sep=',', 
                            dtype=object, 
                            index_col=None,
                            error_bad_lines=False)
print(len(community_layers))
community_layers.head(2)

65956039

,image,layer,level
0,liginccojp:wordpress:1.3.0-php7.1-noinit-apache,sha256:be8881be8156e4068e611fe956aba2b9593ebd9...,0
1,liginccojp:wordpress:1.3.0-php7.1-noinit-apache,sha256:69a25f7e493029f541fc3c7ac66fdffdd5f8c4b...,1

In [72]:
layers.query('image == "library:crate:0.56.4"')

,image,hash,depends,requires
11683,library:crate:0.56.4,e599101eed4f8d1d9a97f115713053ffc535af208788cd...,d24fd36438e5fa304feca7e01bb1b5ef9a23e993fd3433...,dimadavin:dtrlnp:10.0

In [46]:
community_layers.query('image == "abad:dockermentorweek:latest"')

,image,layer,level
34148172,abad:dockermentorweek:latest,sha256:3690ec4760f95690944da86dc4496148a63d85c...,0

In [68]:
official_layers.query('layer == "sha256:02de5b3a42a9987f0e893e1d01a7e0931a7f23749187533accdfdb0e839e1031"')

,image,layer,level
8,library:crate:0.57.5,sha256:02de5b3a42a9987f0e893e1d01a7e0931a7f237...,1
111908,library:crate:0.56.4,sha256:02de5b3a42a9987f0e893e1d01a7e0931a7f237...,1
150399,library:crate:0.57.4,sha256:02de5b3a42a9987f0e893e1d01a7e0931a7f237...,1
154742,library:crate:0.55.7,sha256:02de5b3a42a9987f0e893e1d01a7e0931a7f237...,1
174802,library:crate:0.55,sha256:02de5b3a42a9987f0e893e1d01a7e0931a7f237...,1
192979,library:crate:0.56.3,sha256:02de5b3a42a9987f0e893e1d01a7e0931a7f237...,1
195725,library:crate:0.56,sha256:02de5b3a42a9987f0e893e1d01a7e0931a7f237...,1
199150,library:crate:0.56.2,sha256:02de5b3a42a9987f0e893e1d01a7e0931a7f237...,1

In [41]:
official_layers=pd.read_csv('/home/ahmed/docker_emse/csv/layers_official_may.csv', 
                            sep=',', 
                            dtype=object, 
                            index_col=None,
                            error_bad_lines=False)
print(len(official_layers))
official_layers.head(2)

199637

,image,layer,level
0,library:php:7.2-rc-cli,sha256:bc95e04b23c06ba1b9bf092d07d1493177b218e...,0
1,library:php:7.2-rc-cli,sha256:6a2129b02a8d0ba0faf17a9cfd0faeecfc525cb...,1

In [63]:
layers.query('image == "library:crate:0.57.5"')

,image,hash,depends,requires
0,library:crate:0.57.5,df374273de4cc39786978916764a788d6b6198f7af1bcf...,d24fd36438e5fa304feca7e01bb1b5ef9a23e993fd3433...,dimadavin:dtrlnp:10.0

# Ignore

cases with errors:
official_layers.query('image == "library:crate:0.57.5"')
image = "library:tomcat:8.5.23"